#!/bin/bash

# gdate -d vs bsd date -v -> one gdate to rule them all
# return of 0 is good
function isGNUDate {
        date --version &> /dev/null # only GNU date has this option.
	return $?
}

# what do I have planned for today.
function plan {
	isGNUDate
        if [[ $? -ne 0 ]]; then
                echo "Install GNU Date as date command."
		echo "    ln -s /usr/local/bin/gdate /usr/local/bin/date"
                return 1  # abort
        fi
        local today=$(date +"%Y%m%d")
        local numDayOfWeek=$(date +%u)
        if [[ "$numDayOfWeek" -gt 5 ]]; then
                # it's the weekend, let's look back at Friday's plan
                today=$(date --date="last Fri" +"%Y%m%d")
        fi
        echo "$today"
        echo "/Users/ll/Dropbox/wrk/joyent/scrum/$today-my-scrum"
        cat "/Users/ll/Dropbox/wrk/joyent/scrum/$today-my-scrum"
}


# Work In ProgresED
function wiped {
        local today=$(date +"%Y%m%d")
        for i in $(ls -1 "/Users/ll/Dropbox/wrk/joyent/scrum/" | grep -B 5 "$today-my-scrum"); do
                echo "$i";
                awk '/### Accomplished/ {flag=1;next} /### Planned/{flag=0} flag {print}' \
                        "/Users/ll/Dropbox/wrk/joyent/scrum/$i";
        done
}

# "Everybody has a plan until they get punched in the mouth." ~Mike Tyson
function punched {
        local today=$(date +"%Y%m%d")
        for i in $(ls -1 "/Users/ll/Dropbox/wrk/joyent/scrum/" | grep -B 10 "$today-my-scrum"); do
                sed -n -e '/### Planned/,$p' "/Users/ll/Dropbox/wrk/joyent/scrum/$i";
        done
}

# these mind worms should still be cooking on the stove. If they
# are not they should be moved to task management.
alias mind-worms="vi /Users/ll/Dropbox/wrk/joyent/scrum/back-burner"

# waiting on from other people, but not currently blocking my focus
alias wait-for-it="vi /Users/ll/Dropbox/wrk/joyent/scrum/fill-out-a-request-form"

# my-plan for the next "scrum"
# * If after 09:30 PT then scrumming for the next day.
# * If the weekend, then scrum for Monday.
function my-plan {
	isGNUDate
        if [[ $? -ne 0 ]]; then
                echo "Install GNU Date as date command."
		echo "    ln -s /usr/local/bin/gdate /usr/local/bin/date"
                return 1  # abort
        fi
	local force;
	if [ "$1" == "-f" ]; then
		force="-f"
	fi
	local tz=$(date '+%Z')
	if [[ tz -ne 'PDT' ]]; then
		echo 'Playing safe. Might need to update for PST.'
		echo 'And definitely for other timezones.'
                return 1  # abort
	fi
        local today=$(date '+%Y%m%d')
	local t=$(date '+%H%M')
        local numDayOfWeek=$(date '+%u')
        local nextWorkDay
	local daysAway
        if [[ "$numDayOfWeek" -gt 5 ]]; then
                # it's the weekend, scrumming for Monday
                nextWorkDay=$(date --date='next Mon' '+%Y%m%d')
		daysAway=8-$numDayOfWeek
	elif [[ "$t" < '0930' ]]; then
		# then stil time to scrum for today
                nextWorkDay=$(date '+%Y%m%d')
		daysAway=0
	elif [[ "$numDayOfWeek" -eq 5 ]]; then
		# it's Friday and after 9:30, scrumming for Monday
               	nextWorkDay=$(date --date='next Mon' '+%Y%m%d')
		daysAway=8-$numDayOfWeek
	else
		# scrumming for tomorrow
               	nextWorkDay=$(date --date='next day' '+%Y%m%d')
		daysAway=1
        fi
	echo "MANTA_USER=Joyent_Dev;~/wrk/engdoc/roadmap/bin/scrum $force -d $daysAway -u lloyd < /Users/ll/Dropbox/wrk/joyent/scrum/$nextWorkDay-my-scrum"
	$(MANTA_USER=Joyent_Dev;~/wrk/engdoc/roadmap/bin/scrum "$force" -d "$daysAway" -u lloyd < /Users/ll/Dropbox/wrk/joyent/scrum/"$nextWorkDay"-my-scrum)
}

function morrow {
	isGNUDate
	if [[ $? -ne 0 ]]; then
		echo "Install GNU Date as date command."
		echo "    ln -s /usr/local/bin/gdate /usr/local/bin/date"
		return 1  # abort
	fi
        local today=$(date '+%Y%m%d')
        local numDayOfWeek=$(date +%u)
        local weekday=$(date +"%A")
        local nextWorkDay
        if [[ "$numDayOfWeek" -lt 5 ]]; then
                nextWorkDay=$(date --date="next day" +"%Y%m%d")
        else
                # Don't play work on weekends.
                nextWorkDay=$(date --date="next Mon" +"%Y%m%d")
        fi

        local morrowScrumFile="/Users/ll/Dropbox/wrk/joyent/scrum/$nextWorkDay-my-scrum"

	if [[ ! -f "$morrowScrumFile" ]]; then
		cat << EOF > $morrowScrumFile
mood:

### Accomplished ${weekday}, ${today}
-
-

### Planned For ${nextWorkDay}
-
-
EOF
	fi
	vim -O "/Users/ll/Dropbox/wrk/joyent/scrum/$today-my-scrum" "$morrowScrumFile"
}
